### ISSUE TITLE
Error when installing Rest API Data Localizer plugin 

### ISSUE THREAD

**Issue by sethharris89** [bucky355/vue-wordpress#1]
Hey Bucky! This theme looks like exactly what I am trying to achieve when integrating Vue and Wordpress.

Running into the following issue when installing the localizer plugin:

Warning: require(/app/public/wp-content/plugins/rest-api-data-localizer/store/key/callback.php): failed to open stream: No such file or directory in /app/public/wp-content/plugins/rest-api-data-localizer-master/radl.php on line 62 Fatal error: require(): Failed opening required '/app/public/wp-content/plugins/rest-api-data-localizer/store/key/callback.php' (include_path='.:/usr/share/php:/www/wp-content/pear') in /app/public/wp-content/plugins/rest-api-data-localizer-master/radl.php on line 62 

Running this locally on NGINX / PHP 7.2

Any Idea? Thank you for your work on this.

**Comment by bucky355** [comment]
Change the name of the plugin directory from `rest-api-data-localizer-master` to `rest-api-data-localizer`.

I'll update the autoloader so it's not dependent on the name of the plugin directory, but this should fix it for you.

**Comment by sethharris89** [comment]
That did the trick. thanks!
