### ISSUE TITLE
Theme is not compatible with plugin

### ISSUE THREAD

**Issue by frq6692** [bucky355/vue-wordpress#17]
The plugin rest-api-data-localizer is not working with this theme. I have error after install plugin. Please check thanks
![Untitled](https://user-images.githubusercontent.com/17068280/73769538-a3fda200-479c-11ea-8e7b-cb2dc756b5fa.png)

**Comment by peter-nl** [comment]
It looks to me that you're using rest-api-data-localizer-master as folder name whereas the plugin expects to be insstalled in rest-api-data-localizer and therefor cannot find its components.

**Comment by frq6692** [comment]
Thanks its working now @peter-nl
