### ISSUE TITLE
Using <router-link>?

### ISSUE THREAD

**Issue by psntr** [bucky355/vue-wordpress#19]
I wanted to know why not using the `<router-link>`? We could use the benefit that comes with it, as such as the class="active" on the current & clicked nav item.

How do other folks deal with the class="active" on their theme?

**Comment by omaratta2** [comment]
I'd struggled sometimes with that, then I used <router-link> any way.
**Why the theme doesn't use router-link?**
Let's say that you have an article with an internal link, like a link to about page for example. you have two options.
1. Use <router-link> but then the 'to' attribute will hold the whole URL not just the route and it will fail.
2. use <a> tag and it will reload the entire page so the app isn't SPA anymore!

This theme solves the problem using internal link deligation which is explained in detail in the readme, yet I find confusing & especially for the "active" class.

**Another solution**
Using this method could be helpful, you will need to pass any URL of this type to that method first
```javascript
function routeFromLink(url){
    const siteUrl = this.$store.state.site.url
    if(url.includes(siteUrl)) return url.replace(siteUrl, '')
    else return '/'
}
```
Then in the navbar:
```javascript
<route-link v-for="item in menu" :to="routeFromLink(item.url)">{{ item.content }}</route-link>
```

**Comment by psntr** [comment]
Thank you, that's a clever way to solve that. Also thank you for explaining further reason, I didn't think about the internal links. Hope someone will find this helpful!
