### ISSUE TITLE
Buddypress integration

### ISSUE THREAD

**Issue by shubhra14** [bucky355/vue-wordpress#2]
I am wondering if it's possible to integrate this [BP rest api plugin](https://github.com/buddypress/BP-REST) in this theme. If so, can you please explain a bit, how to go about it.

Thank you for your time and thank you for making this theme. Having fun learning here.

**Comment by bucky355** [comment]
Depends how you would want to integrate it. It would be easiest to just use it within your components without having to worry about making requests internally.

More like a starter for creating themes than an actual theme. Needs work, but provides a solid foundation conceptually I think. Glad you're learning from it.
