### ISSUE TITLE
Doesn't work if slug contains HTML entities

### ISSUE THREAD

**Issue by shubhra14** [bucky355/vue-wordpress#4]
Hi again,
Another small issue. It fails to fetch the data if the slug contains html entities ```/wp-json/wp/v2/pages/?slug=this-is-a-%E0%A5%90-page```. Happens with posts as well as pages.

**Comment by bucky355** [comment]
Are you sure that's the slug WP is generating?

I'll look into it later.

**Comment by shubhra14** [comment]
Yes, its coming from WP. I can access the post if I visit the api link directly, however, the "post" is undefined in the vue development tab
![wp-json](https://user-images.githubusercontent.com/5490862/57984309-38da3700-7a78-11e9-88e6-a2ea73fb901b.jpg)
![vue-tab](https://user-images.githubusercontent.com/5490862/57984310-38da3700-7a78-11e9-8c60-a0e1a34e1854.jpg)
![network-tab](https://user-images.githubusercontent.com/5490862/57984311-38da3700-7a78-11e9-98be-273510914ea4.jpg)

**Comment by shubhra14** [comment]
Sorry to bother you with this, did you find the time to look at this issue?

I would love wider knowledge on why it could be happening and I can try and troubleshoot it. Thank you!

**Comment by bucky355** [comment]
Ya sorry, have been busy the past week. Will look into it either tonight or tomorrow and apply a fix.

If it's something that'll take longer to fix, I'll provide some direction, so you can implement those changes.

Apologize for the delayed response.

**Comment by shubhra14** [comment]
It is perfectly fine. I appreciate you helping me out.

**Comment by bshiluk** [comment]
Fixed in latest update.

The `singleBySlug` getter was comparing an encoded slug to a decoded slug, resulting in a 404. 
Just used [`decodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) to ensure consistency.

Should for sure work for you, but let me know.

**Comment by shubhra14** [comment]
It works. Thank you!

I have learned so much digging into this. I am not a developer, however, its amazing how easy it is to build on top of this bundle once you learn the basics. Appreciate you sharing it with us.

Looking forward to more features ;)
